import { S, GLOBAL_CSS } from "../styles/styles";
import Topbar from "./Topbar";
// Static data is the fallback if aiResult is not available
import { DATA, FALLBACK } from "../data/roleData";

// ── CERTIFICATES PAGE ──────────────────────────────────────────
// Renders certs from state.aiResult (OpenAI) if available,
// otherwise falls back to the static roleData.
export default function CertsPage({ onNavigate, state }) {
  const aiResult = state.aiResult;

  // Prefer AI-generated certs; fall back to static data
  const certs = aiResult?.certs?.length
    ? aiResult.certs
    : (DATA[state.role] || FALLBACK).certs;

  const roleLabel = state.role || "your target role";
  const isAI      = !!aiResult?.certs?.length;

  return (
    <div style={{ ...S.page, background: "#F8FAFC" }}>
      <style>{GLOBAL_CSS}</style>
      <Topbar onBack={() => onNavigate("upload")} backLabel="Back to Analysis" />

      <div style={{ padding: "40px 5vw 60px" }}>

        {/* Header */}
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 14, flexWrap: "wrap" }}>
          <span style={{ ...S.sectionBadge, display: "inline-flex" }}>
            🎓 Personalized for your gaps
          </span>
          {isAI && (
            <span style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 14px", borderRadius: 99, background: "linear-gradient(135deg,#EFF6FF,#DBEAFE)", border: "1.5px solid #BFDBFE", color: "#2563EB", fontSize: 12, fontWeight: 800 }}>
              🤖 Generated by OpenAI GPT-4o
            </span>
          )}
        </div>

        <h1 style={{ fontSize: "clamp(28px,3.5vw,46px)", fontWeight: 900, color: "#111827", letterSpacing: -1.5, fontFamily: "'Sora', sans-serif", lineHeight: 1.12, marginBottom: 12 }}>
          Certificate Recommendations
        </h1>
        <p style={{ fontSize: 15, color: "#6B7280", marginBottom: 32, lineHeight: 1.7, maxWidth: 580 }}>
          {isAI
            ? `${certs.length} high-impact certifications recommended by AI for ${roleLabel} — ranked by gap coverage and current market demand.`
            : `6 high-impact certifications for ${roleLabel} — ranked by gap coverage and market demand.`}
        </p>

        {/* Cert cards grid */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(320px,1fr))", gap: 22 }}>
          {certs.map((c, i) => (
            <div key={i} className="cert-card" style={{ animationDelay: `${i * 0.08}s` }}>

              {/* Icon */}
              <div style={{ width: 50, height: 50, borderRadius: 15, background: "linear-gradient(135deg,#EFF6FF,#DBEAFE)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, marginBottom: 16 }}>
                {c.icon || "🎓"}
              </div>

              {/* Title + platform */}
              <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 10, marginBottom: 10 }}>
                <div style={{ fontSize: 16, fontWeight: 800, color: "#111827", fontFamily: "'Sora', sans-serif", letterSpacing: -0.3, lineHeight: 1.3 }}>
                  {c.title}
                </div>
                <span style={{ flexShrink: 0, fontSize: 11, fontWeight: 800, padding: "4px 10px", borderRadius: 8, background: "#F3F4F6", color: "#374151", border: "1px solid #E5E7EB", whiteSpace: "nowrap" }}>
                  {c.platform}
                </span>
              </div>

              {/* Why this cert */}
              <div style={{ background: "#F0FDF4", border: "1px solid #6EE7B7", borderRadius: 10, padding: "10px 14px", marginBottom: 12, fontSize: 12.5, color: "#065F46", lineHeight: 1.65, fontWeight: 600 }}>
                <strong style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: 0.5, display: "block", marginBottom: 4, color: "#047857" }}>💡 Why this cert?</strong>
                {c.why}
              </div>

              {/* Description */}
              <div style={{ fontSize: 13, color: "#6B7280", lineHeight: 1.7, marginBottom: 14 }}>{c.desc}</div>

              {/* Tags */}
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 14 }}>
                {(c.tags || []).map((t) => (
                  <span key={t} style={{ background: "#EFF6FF", color: "#2563EB", border: "1px solid #BFDBFE", fontSize: 11, padding: "3px 9px", borderRadius: 99, fontWeight: 700 }}>{t}</span>
                ))}
              </div>

              <div style={{ height: 1, background: "#E5E7EB", margin: "14px 0" }} />

              {/* CTA */}
              <a className="cert-link" href={c.link} target="_blank" rel="noopener noreferrer">
                View Certificate
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="7" y1="17" x2="17" y2="7" /><polyline points="7 7 17 7 17 17" />
                </svg>
              </a>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}