import { S, GLOBAL_CSS } from "../styles/styles";
import Topbar from "./Topbar";
import { DATA, FALLBACK } from "../data/roleData";

const DIFF_STYLES = {
  easy: { bg: "#ECFDF5", color: "#059669", border: "#6EE7B7", label: "● Beginner",     weeks: "< 1 week"   },
  mid:  { bg: "#FFFBEB", color: "#D97706", border: "#FDE68A", label: "● Intermediate", weeks: "1–3 weeks"  },
  hard: { bg: "#FFF1F2", color: "#E11D48", border: "#FECDD3", label: "● Advanced",     weeks: "3–8 weeks"  },
};

export default function ProjectsPage({ onNavigate, state }) {
  const aiResult  = state.aiResult;
  const projects  = aiResult?.projects?.length
    ? aiResult.projects
    : (DATA[state.role] || FALLBACK).projects;
  const roleLabel = state.role || "your target role";
  const isAI      = !!aiResult?.projects?.length;

  return (
    <div style={{ ...S.page, background: "#F8FAFC" }}>
      <style>{GLOBAL_CSS}</style>
      <Topbar onBack={() => onNavigate("upload")} backLabel="Back to Analysis" />

      <div style={{ padding: "40px 5vw 80px", maxWidth: 1200, margin: "0 auto" }}>

        {/* ── Header ── */}
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 14, flexWrap: "wrap" }}>
          <span style={{ ...S.sectionBadge, display: "inline-flex" }}>🚀 Build your portfolio</span>
          {isAI && (
            <span style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 14px", borderRadius: 99, background: "linear-gradient(135deg,#ECFDF5,#D1FAE5)", border: "1.5px solid #6EE7B7", color: "#059669", fontSize: 12, fontWeight: 800 }}>
              🤖 Generated by Gemini AI
            </span>
          )}
        </div>

        <h1 style={{ fontSize: "clamp(28px,3.5vw,46px)", fontWeight: 900, color: "#111827", letterSpacing: -1.5, fontFamily: "'Sora', sans-serif", lineHeight: 1.12, marginBottom: 10 }}>
          Project Recommendations
        </h1>
        <p style={{ fontSize: 15, color: "#6B7280", marginBottom: 32, lineHeight: 1.7, maxWidth: 600 }}>
          {isAI
            ? `${projects.length} projects AI-tailored for ${roleLabel} — each one directly closes a specific skill gap in your profile.`
            : `Hands-on projects for ${roleLabel} — designed to close your skill gaps and impress recruiters.`}
        </p>

        {/* ── Summary: gaps addressed ── */}
        {isAI && aiResult?.gaps?.length > 0 && (
          <div style={{ background: "#fff", borderRadius: 16, border: "1.5px solid #DBEAFE", padding: "16px 20px", marginBottom: 28, display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}>
            <span style={{ fontSize: 12, fontWeight: 800, color: "#6B7280" }}>Gaps covered by these projects:</span>
            {aiResult.gaps.map((g) => (
              <span key={g} style={{ background: "#EFF6FF", color: "#2563EB", border: "1px solid #BFDBFE", borderRadius: 8, padding: "3px 10px", fontSize: 12, fontWeight: 700 }}>{g}</span>
            ))}
          </div>
        )}

        {/* ── Project grid ── */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(340px,1fr))", gap: 22 }}>
          {projects.map((p, i) => {
            const diff = DIFF_STYLES[p.difficulty] || DIFF_STYLES.mid;
            return (
              <div key={i} className="proj-card" style={{ animationDelay: `${i * 0.08}s` }}>

                {/* Card header */}
                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 16 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                    <div style={{ width: 52, height: 52, borderRadius: 16, background: "linear-gradient(135deg,#ECFDF5,#D1FAE5)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 24, flexShrink: 0 }}>
                      {p.icon || "🛠️"}
                    </div>
                    <div>
                      <span style={{ display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11, fontWeight: 800, padding: "4px 10px", borderRadius: 99, background: diff.bg, color: diff.color, border: `1px solid ${diff.border}`, marginBottom: 4 }}>
                        {diff.label}
                      </span>
                      <div style={{ fontSize: 11, color: "#9CA3AF", fontWeight: 600 }}>⏱ {diff.weeks}</div>
                    </div>
                  </div>
                  <span style={{ fontSize: 11, fontWeight: 800, color: "#6B7280", background: "#F8FAFC", border: "1px solid #E5E7EB", borderRadius: 8, padding: "4px 8px", flexShrink: 0 }}>
                    #{i + 1}
                  </span>
                </div>

                {/* Title */}
                <div style={{ fontSize: 16, fontWeight: 800, color: "#111827", marginBottom: 10, fontFamily: "'Sora', sans-serif", letterSpacing: -0.3, lineHeight: 1.35 }}>
                  {p.title}
                </div>

                {/* Description */}
                <div style={{ fontSize: 13, color: "#6B7280", lineHeight: 1.75, marginBottom: 14 }}>
                  {p.desc}
                </div>

                {/* Gap addressed badge (AI only) */}
                {isAI && p.gap_addressed && (
                  <div style={{ background: "#FFF7ED", border: "1px solid #FDE68A", borderRadius: 10, padding: "8px 12px", marginBottom: 12, fontSize: 12, color: "#92400E", fontWeight: 700, display: "flex", alignItems: "flex-start", gap: 6 }}>
                    <span>🎯</span>
                    <span>Closes gap: <strong>{p.gap_addressed}</strong></span>
                  </div>
                )}

                {/* Outcome badge (AI only) */}
                {isAI && p.outcome && (
                  <div style={{ background: "#F0FDF4", border: "1px solid #6EE7B7", borderRadius: 10, padding: "8px 12px", marginBottom: 14, fontSize: 12, color: "#065F46", fontWeight: 700, display: "flex", alignItems: "flex-start", gap: 6 }}>
                    <span>✨</span>
                    <span>Portfolio outcome: {p.outcome}</span>
                  </div>
                )}

                {/* Skill tags */}
                <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}>
                  {(p.skills || []).map((s) => (
                    <span key={s} style={{ background: "#ECFEFF", color: "#0891B2", border: "1px solid #A5F3FC", fontSize: 11, padding: "4px 10px", borderRadius: 99, fontWeight: 700 }}>{s}</span>
                  ))}
                </div>

                {/* Spacer push */}
                <div style={{ flex: 1 }} />

                <div style={{ height: 1, background: "#E5E7EB", margin: "0 0 14px" }} />

                {/* Links */}
                <div style={{ display: "flex", gap: 9, flexWrap: "wrap" }}>
                  <a className="proj-link" href={p.gh} target="_blank" rel="noopener noreferrer">
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22" />
                    </svg>
                    GitHub Topics
                  </a>
                  <a className="proj-link proj-link-yt" href={p.yt} target="_blank" rel="noopener noreferrer">
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <polygon points="5 3 19 12 5 21 5 3" />
                    </svg>
                    Watch Tutorial
                  </a>
                </div>
              </div>
            );
          })}
        </div>

        {/* ── Bottom nav ── */}
        <div style={{ marginTop: 40, display: "flex", gap: 14, flexWrap: "wrap" }}>
          <button onClick={() => onNavigate("analytics")} style={{ ...S.btnPrimary, fontSize: 14, padding: "13px 24px" }}>
            📊 View Analytics Dashboard
          </button>
          <button onClick={() => onNavigate("career")} style={{ ...S.btnOutline, fontSize: 14, padding: "12px 24px" }}>
            🗺️ View Career Roadmap
          </button>
        </div>
      </div>
    </div>
  );
}